export const PRESETS = {
  'figlet-dos-rebel-main': {
    label: 'DOS Rebel Main',
    engine: 'figlet',
    family: 'figlet',
    intent: 'Default README fallback wordmark. Dense, structured, and tool-like.',
    defaultPalette: 'ocean',
    fontKey: 'dos-rebel',
    caseKey: 'upper',
    layout: 'stacked',
    align: 'left',
    cellW: 8,
    cellH: 12,
    letterGap: 2,
    lineGap: 5,
    wordGap: 5,
    pad: 14,
    darken: 0.52,
    gradientDirection: 'horizontal',
  },
  'figlet-dos-rebel-inline': {
    label: 'DOS Rebel Inline',
    engine: 'figlet',
    family: 'figlet',
    intent: 'Softer secondary DOS Rebel variant for smaller or more product-like README headers.',
    defaultPalette: 'sunset',
    fontKey: 'dos-rebel',
    caseKey: 'title',
    layout: 'inline',
    align: 'center',
    cellW: 7,
    cellH: 12,
    letterGap: 1,
    lineGap: 5,
    wordGap: 4,
    pad: 12,
    darken: 0.52,
    gradientDirection: 'horizontal',
  },
  'figlet-ansi-shadow-sharp': {
    label: 'ANSI Shadow Sharp',
    engine: 'figlet',
    family: 'figlet',
    intent: 'Poster-like alternative with a sharper shadow split.',
    defaultPalette: 'solar-flare',
    fontKey: 'ansi-shadow',
    caseKey: 'upper',
    layout: 'stacked',
    align: 'center',
    cellW: 8,
    cellH: 14,
    letterGap: 2,
    lineGap: 6,
    wordGap: 5,
    pad: 14,
    darken: 0.56,
    gradientDirection: 'horizontal',
  },
  'cfonts-console-neutral': {
    label: 'Console Neutral',
    engine: 'cfonts',
    family: 'cfonts',
    intent: 'Quiet and minimal. Useful as a neutral fallback or control.',
    defaultPalette: 'sunset',
    font: 'console',
    variantKey: 'neutral',
    darken: 0.48,
    pad: 14,
  },
  'cfonts-block-compact': {
    label: 'Block Compact',
    engine: 'cfonts',
    family: 'cfonts',
    intent: 'Structured and display-ready. Strongest general-purpose cfonts baseline.',
    defaultPalette: 'ocean',
    font: 'block',
    variantKey: 'compact',
    cellW: 10,
    cellH: 16,
    shadowOffset: 2,
    darken: 0.48,
    pad: 12,
  },
  'cfonts-simpleblock-slim': {
    label: 'SimpleBlock Slim',
    engine: 'cfonts',
    family: 'cfonts',
    intent: 'Slimmer block texture when the main block preset feels too heavy.',
    defaultPalette: 'ocean',
    font: 'simpleBlock',
    variantKey: 'slim',
    cellW: 9,
    cellH: 18,
    shadowOffset: 2,
    darken: 0.48,
    pad: 16,
  },
  'cfonts-shade-default': {
    label: 'Shade Default',
    engine: 'cfonts',
    family: 'cfonts',
    intent: 'Soft metallic texture with readable structure.',
    defaultPalette: 'forest',
    font: 'shade',
    variantKey: 'default',
    cellW: 10,
    cellH: 16,
    shadowOffset: 2,
    darken: 0.4,
    pad: 14,
  },
  'cfonts-shade-crisp': {
    label: 'Shade Crisp',
    engine: 'cfonts',
    family: 'cfonts',
    intent: 'Brighter and cleaner shade treatment with more snap.',
    defaultPalette: 'ocean',
    font: 'shade',
    variantKey: 'crisp',
    cellW: 9,
    cellH: 16,
    shadowOffset: 2,
    darken: 0.32,
    pad: 15,
  },
  'cfonts-tiny-tall': {
    label: 'Tiny Tall',
    engine: 'cfonts',
    family: 'cfonts',
    intent: 'Compact micro-display style with distinct personality.',
    defaultPalette: 'ocean',
    font: 'tiny',
    variantKey: 'tall',
    cellW: 9,
    cellH: 20,
    shadowOffset: 2,
    darken: 0.48,
    pad: 18,
  },
};

export const BASELINE_PACK = [
  'figlet-dos-rebel-main',
  'figlet-dos-rebel-inline',
  'cfonts-block-compact',
  'cfonts-simpleblock-slim',
  'cfonts-shade-default',
  'cfonts-shade-crisp',
  'cfonts-tiny-tall',
];

export const EXAMPLE_JOBS = [
  // figlet presets
  { name: 'readme-craft', preset: 'figlet-dos-rebel-inline', palette: 'ocean' },
  { name: 'readme-craft', preset: 'figlet-dos-rebel-main', palette: 'solar-flare' },
  { name: 'readme-craft', preset: 'figlet-ansi-shadow-sharp', palette: 'synthwave' },
  // cfonts presets — each preset once, different names + palettes
  { name: 'readme-craft', preset: 'cfonts-block-compact', palette: 'arctic' },
  { name: 'skill-forge', preset: 'cfonts-shade-crisp', palette: 'voltage' },
  { name: 'repo-scaffold', preset: 'cfonts-tiny-tall', palette: 'plasma' },
  { name: 'readme-craft', preset: 'cfonts-simpleblock-slim', palette: 'ultraviolet' },
  { name: 'readme-craft', preset: 'cfonts-shade-default', palette: 'forest' },
  { name: 'readme-craft', preset: 'cfonts-console-neutral', palette: 'midnight' },
];

export const HEADER_STYLE_PRESETS = {
  'single-line': 'figlet-dos-rebel-inline',
  stacked: 'figlet-dos-rebel-main',
  block: 'cfonts-block-compact',
};

export const RELIABLE_POOL = [
  'figlet-dos-rebel-main',
  'figlet-dos-rebel-inline',
  'figlet-ansi-shadow-sharp',
  'cfonts-block-compact',
  'cfonts-shade-crisp',
  'cfonts-tiny-tall',
];

export function resolvePresetChoice(presetKey, headerStyle) {
  if (presetKey) return presetKey;
  const styleKey = headerStyle ?? 'single-line';
  const resolved = HEADER_STYLE_PRESETS[styleKey];
  if (!resolved) {
    throw new Error(`Unknown header style: ${styleKey}. Available: ${Object.keys(HEADER_STYLE_PRESETS).join(', ')}`);
  }
  return resolved;
}
